"""add creator to country

Revision ID: 0c96b40927f9
Revises: 5d4af7ff9fb2
Create Date: 2025-08-05 00:16:50.311549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c96b40927f9'
down_revision: Union[str, Sequence[str], None] = '5d4af7ff9fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('creator_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'creator_id')
    # ### end Alembic commands ###
