"""timestamp field for last roll table

Revision ID: 580cb9a66459
Revises: 73493bb59056
Create Date: 2025-08-19 19:30:31.265989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580cb9a66459'
down_revision: Union[str, Sequence[str], None] = '73493bb59056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_roll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_roll', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
