"""per game unique constraints fix

Revision ID: cbb7fc8f8e30
Revises: a4cdd2d61404
Create Date: 2025-08-08 14:51:37.162700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb7fc8f8e30'
down_revision: Union[str, Sequence[str], None] = 'a4cdd2d61404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_country_color'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_country_name'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_country_game_id_color'), ['game_id', 'color'])
        batch_op.create_unique_constraint(batch_op.f('uq_country_game_id_name'), ['game_id', 'name'])

    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tile_code'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_tile_game_id_code'), ['game_id', 'code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tile_game_id_code'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_tile_code'), ['code'])

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_country_game_id_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_country_game_id_color'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_country_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_country_color'), ['color'])

    # ### end Alembic commands ###
